# Test
language: c
compiler:
  - gcc
#  - clang
env:
  - BUILDTYPE=cmake-make
  - BUILDTYPE=cmake-ninja
  - BUILDTYPE=autotools
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq gnucash
  - sudo apt-get install -qq swig xsltproc libdbd-sqlite3 cmake3 texinfo ninja-build
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
script: ./util/travis-script.sh
after_failure:  ./util/travis-after-failure.sh
